import '../styles/globals.css'
import Head from 'next/head'
import { useCounter } from '../hooks/useCounter';

function MyApp({ Component, pageProps }) {
  const counter = useCounter();
  return (
    <div>
       <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Component {...pageProps} {...counter} />
    </div>)
   
}

export default MyApp
